propose:
  description: >
    your task is to propose in favour of the topic {topic}
    Provide clear and convincing arguments in favour of the topic: {topic} that is relevant and interesting.
  expected_output: >
    A list with 10 bullet points of the most convinving arguments favoured about the topic
  agent: debater
  output_file: output/propose.md

oppose:
  description: >
    your task is to oppose the topic {topic}
    Provide clear and convincing arguments in against of the topic: {topic} that is relevant and interesting.
  expected_output: >
    A list with 10 bullet points of the most convinving arguments against the topic
  agent: debater
  output_file: output/oppose.md
decide:
  description: >
    Review the arguments presented by the debaters and decide which side is more convincing.
  expected_output: >
    Two sections:
    Verdict: in favour of the topic - {topic} or against the topic - {topic}
    Reason : it states the decision on which side is more convincing, and why within 200 words covering all points.
  agent: judge
  output_file: output/decide.md